name: Sanity Testing 
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress-cypress-addtoCart-flow


      - name: Cypress Test Report 
        uses: actions/upload-artifact@v4
        with:
          name: Mochaweson HTML Reports
          path: cypress/reports/html


